import Head from "next/head";
import SiderBar from "../components/SideBar";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black   min-h-screen  lg:flex my-0 mx-auto lg:max-w-[1600px] xl:max-w-[1400px]">
        <SiderBar />
        <Feed />
      </main>
    </div>
  );
}
